# Generated by Django 5.2 on 2026-04-01 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookreserve", "0007_bookrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreserve",
            name="picture",
            field=models.ImageField(default="", upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="bookreserve",
            name="publication_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="出版日"
            ),
        ),
        migrations.AlterField(
            model_name="bookreserve",
            name="reservation_availability",
            field=models.BooleanField(default=True, verbose_name="予約可否"),
        ),
    ]
