# Generated by Django 5.2 on 2026-04-02 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookreserve", "0008_alter_bookreserve_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreserve",
            name="publication_date",
            field=models.DateField(default=datetime.date.today, verbose_name="出版日"),
        ),
    ]
